version: '3.8'

services:
  jessy-academia:
    build: .
    container_name: jessy-academia
    restart: always
    expose:
      - "80"
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
